version: '3.8'
services:
  mongodb:
    image: mongo:5
    container_name: library-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=userdb
    networks:
      - library-network

  postgres:
    image: postgres:14
    container_name: library-postgres
    environment:
      - POSTGRES_DB=bookdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data: