server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# Configuration pour Feign avec circuit breaker
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        